rabbitmq:
  image: 'rabbitmq:3-management-alpine'
  container_name: 'rabbitmq-gisa'
  restart: unless-stopped
  ports:
    - "5672:5672"
    - "15672:15672"
  environment:
    RABBITMQ_DEFAULT_USER: guest
    RABBITMQ_DEFAULT_PASSWORD: guest
    RABBITMQ_DEFAULT_VHOST: /